[parity]
chain = "spec.json"
base_path = "/0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "parity_pubsub"]
[ui]
port = 8182
[websockets]
port = 8450
[account]
password = ["node0.pwds"]
[mining]
engine_signer = "0x00dd2ecedfc0034ace4f59375d5836165c72b492"
reseal_on_txs = "none"
usd_per_tx = "0"
extra_data = "Msft0"