[parity]
chain = "spec.json"
base_path = "/1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[websockets]
port = 8451
[ipc]
disable = true
[account]
password = ["node1.pwds"]
[mining]
engine_signer = "0x006a1a9b464a7808b0a2645ea62c15eb33615e29"
reseal_on_txs = "none"
usd_per_tx = "0"
extra_data = "Msft1"