[parity]
chain = "spec.json"
base_path = "/3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8184
[websockets]
port = 8453
[ipc]
disable = true
[account]
password = ["node3.pwds"]
[mining]
engine_signer = "0x0011e3cdc7bb6e23b6b50fd8c7ba416aa3ccab94"
reseal_on_txs = "none"
usd_per_tx = "0"
extra_data = "UBS1"